//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_AVIS_AVI
    {
        public int CPT_ID { get; set; }
        public int FLM_ID { get; set; }
        public System.DateTime AVI_DATE { get; set; }
        public string AVI_TITRE { get; set; }
        public string AVI_DETAIL { get; set; }
        public decimal AVI_NOTE { get; set; }
    
        public virtual T_E_COMPTE_CPT Compte { get; set; }
        public virtual T_E_FILM_FLM Film { get; set; }
    }
}
